CREATE TABLE IF NOT EXISTS
user_account (
    id UUID PRIMARY KEY NOT NULL,
    full_name VARCHAR(300) NOT NULL,
    email VARCHAR(150) NOT NULL,
    customer_password VARCHAR(150) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
