CREATE TABLE IF NOT EXISTS
subscription (
    id UUID PRIMARY KEY NOT NULL,
    full_name VARCHAR(300) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
